import type { Metadata } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { SEQUENCE_FRAMES } from "@/lib/sequence-frames";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif-4",
  subsets: ["latin"],
  style: ["normal", "italic"],
  axes: ["opsz"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${sourceSerif.variable} h-full antialiased`}
    >
      <head>
        {/*
          Preload the entire scroll sequence at the document level so it starts
          fetching before hydration. Frame 0 is highest priority (it's the
          placeholder); the rest stream in behind it as low priority.
        */}
        {SEQUENCE_FRAMES.map((src, index) => (
          <link
            key={src}
            rel="preload"
            as="image"
            href={src}
            fetchPriority={index === 0 ? "high" : "low"}
          />
        ))}
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
