import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { SEQUENCE_FRAMES } from "@/lib/sequence-frames";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full bg-black antialiased",
        inter.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <head>
        {/*
          Preload the entire scroll sequence at the document level so it starts
          fetching before hydration. Frame 0 is highest priority (it's the
          placeholder); the rest stream in behind it as low priority.
        */}
        {SEQUENCE_FRAMES.map((src, index) => (
          <link
            key={src}
            rel="preload"
            as="image"
            href={src}
            fetchPriority={index === 0 ? "high" : "low"}
          />
        ))}
      </head>
      <body className={cn(inter.className, "min-h-full bg-black text-foreground")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
